endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\WebPWriter
        size: 300
        margin: 10
        encoding: 'UTF-8'
        error_correction_level: 'low'
        round_block_size_mode: 'margin'
        validate_result: false
